

	TITLE	"EZIP/6502 INFOCOM, INC. --- EQUATES"

	; --------------------------
	; EZIP/6502 2.0
	; Z-CODE INTERPRETER PROGRAM
	; FOR APPLE IIE/IIC
	; --------------------------

	; INFOCOM, INC.
	; 125 CAMBRIDGEPARK DRIVE
	; CAMBRIDGE, MA 02140

	; COMPANY PRIVATE -- NOT FOR DISTRIBUTION

DEBUG	EQU	1		; ASSEMBLY FLAG FOR DEBUGGER (1 = YES)

	; -----------
	; ERROR CODES
	; -----------

	; 00 -- INSUFFICIENT RAM
	; 01 -- ILLEGAL X-OP
	; 02 -- ILLEGAL 0-OP
	; 03 -- ILLEGAL 1-OP
	; 04 -- ILLEGAL 2-OP
	; 05 -- Z-STACK UNDERFLOW
	; 06 -- Z-STACK OVERFLOW
	; 07 -- ILLEGAL PROPERTY LENGTH (GETP)
	; 08 -- DIVISION BY ZERO
	; 09 -- ILLEGAL ARGUMENT COUNT (EQUAL?)
	; 10 -- ILLEGAL PROPERTY ID (PUTP)
	; 11 -- ILLEGAL PROPERTY LENGTH (PUTP)
	; 12 -- DISK ADDRESS OUT OF RANGE
	; 13 -- IMPURE CODE TOO LARGE (BM 1/20/86)
	; 14 -- DRIVE ACCESS
	; 15 -- NOT AN EZIP GAME
	; 16 -- ILLEGAL EXTENDED RANGE X-OP

	INCLUD 	EQ.SRC


	TITLE 	"ZIP/6502 INFOCOM, INC. --- MACHINE DEPENDENT SHELL"
	INCLUD 	HARDEQ.SRC
	INCLUD	RWTS.SRC
	INCLUD	ZDOS.SRC
	INCLUD	MACHINE.SRC
	INCLUD 	COLD.SRC

	TITLE 	"ZIP/6502 INFOCOM, INC. --- INIT & MAINLINE"
	INCLUD 	WARM.SRC
	INCLUD 	MAIN.SRC
	INCLUD 	SUBS.SRC
	INCLUD 	DISPATCH.SRC

	TITLE 	"ZIP/6502 INFOCOM, INC. --- OPCODE EXECUTORS"
	INCLUD 	OPS012.SRC
	INCLUD 	OPSX.SRC
	INCLUD 	READ.SRC

	TITLE 	"ZIP/6502 INFOCOM, INC. --- OP SUPPORT & MEMORY MANAGEMENT"

	INCLUD 	XPAGING.SRC
	INCLUD 	ZSTRING.SRC
	INCLUD 	OBJECTS.SRC

	TITLE 	"ZIP/6502 INFOCOM, INC. --- MACHINE DEPENDENT SHELL"

	INCLUD	IO.SRC			; (EZIP SO COLD IS ON 1ST TRACK)

	IF	DEBUG
	INCLUD	BUGGER.SRC
	ENDIF

	END

